language: generic
matrix:
  include:
    - os: windows
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          
      
script:
  - mkdir build && cd build
  - cmake .. && make
  - ./tests -s -r compact
