language: generic
matrix:
  include:
    - os: linux
      sudo: required
      env: COMPILER=g++ -std=c++11
      addons:
        apt:
          packages:
            - g++-4
            - cmake
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
          
      
script:
  - mkdir build && cd build
  - cmake .. && make
  - ./tests -s -r compact
